// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUW2KOtbm6RgHnj5RxhBJrvuMUNUmEYiU',
    appId: '1:673634928046:android:52ea87578a78f61eee343f',
    messagingSenderId: '673634928046',
    projectId: 'fir-auth-f0b4b',
    databaseURL: 'https://fir-auth-f0b4b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-f0b4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyMH2V8799qG8L6UbFp98jrkzYMAuBVgU',
    appId: '1:673634928046:ios:498ae01e6940090bee343f',
    messagingSenderId: '673634928046',
    projectId: 'fir-auth-f0b4b',
    databaseURL: 'https://fir-auth-f0b4b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-f0b4b.firebasestorage.app',
    iosBundleId: 'com.example.firebasePushNotification',
  );
}
